// scripts/build.ts — 构建单文件可执行（前端资源嵌入 exe）
import { readFileSync, writeFileSync, unlinkSync } from "fs";
import { join } from "path";
import { $ } from "bun";

const OUT_NAME = "buddy-reroller";
const ROOT = import.meta.dir.replace(/[\\/]scripts$/, "");
const EMBEDDED_PATH = join(ROOT, "src", "_embedded-frontend.ts");

// 1. Build frontend bundle
console.log("Building frontend bundle...");
const frontendResult = await Bun.build({
  entrypoints: [join(ROOT, "frontend", "entry.tsx")],
  outdir: join(ROOT, "dist", "frontend"),
  target: "browser",
  minify: true,
  sourcemap: "none",
});

if (!frontendResult.success) {
  console.error("Frontend build failed:");
  for (const log of frontendResult.logs) console.error(log);
  process.exit(1);
}

// Read frontend assets
let bundleJS: Uint8Array | null = null;
for (const output of frontendResult.outputs) {
  if (output.path.endsWith(".js")) {
    bundleJS = readFileSync(output.path);
    console.log(`  Bundle: ${output.path.split(/[\\/]/).pop()} (${(bundleJS.length / 1024).toFixed(1)}KB)`);
  }
}

const cssContent = readFileSync(join(ROOT, "frontend", "styles.css"), "utf-8");
const htmlContent = readFileSync(join(ROOT, "frontend", "index.html"), "utf-8");

// 2. Write embedded assets module
console.log("Embedding frontend assets...");
const embeddedCode = `// Auto-generated by build.ts — do not commit
export const EMBEDDED_JS = new Uint8Array([${bundleJS ? Array.from(bundleJS).join(",") : ""}]);
export const EMBEDDED_CSS = ${JSON.stringify(cssContent)};
export const EMBEDDED_HTML = ${JSON.stringify(htmlContent)};
`;
writeFileSync(EMBEDDED_PATH, embeddedCode);

// 3. Compile server (will include embedded assets via static import)
console.log("Compiling server...");
try {
  const result = await $`bun build --compile --minify --outfile ${OUT_NAME}${process.platform === "win32" ? ".exe" : ""} ./src/server.ts`.cwd(ROOT);

  if (result.exitCode !== 0) {
    console.error("Server compile failed");
    process.exit(1);
  }
} finally {
  // Clean up embedded file
  try { unlinkSync(EMBEDDED_PATH); } catch {}
}

console.log(`\n  ✅ Built: ${OUT_NAME}${process.platform === "win32" ? ".exe" : ""}`);
console.log(`  Run: ./${OUT_NAME}${process.platform === "win32" ? ".exe" : ""}\n`);
